version: '3'

services:
  db:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=500' -c 'shared_buffers=1024' -c 'log_min_messages=notice'
    restart: always
    environment:
      POSTGRES_DB: zeusssss
      POSTGRES_USER: zeus
      POSTGRES_PASSWORD: "zeusisdemax"
      TZ: Europe/Brussels
      PGTZ: Europe/Brussels
    volumes:
      - pgdata-zeusss:/var/lib/postgresql/data
  zeusss:
    build:
      context: .
      tags:
        - "zeusss:latest"
    depends_on:
      - db
    container_name: zeusss
    ports:
      - "8080:8080"

volumes:
  pgdata-zeusss:
